/*
 * This file is generated by jOOQ.
 */
package org.example.repositories.jooqGenEntities;


import javax.annotation.processing.Generated;

import org.example.repositories.jooqGenEntities.tables.Cat;
import org.example.repositories.jooqGenEntities.tables.CatCat;
import org.example.repositories.jooqGenEntities.tables.Owner;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.cat</code>.
     */
    public static final Cat CAT = Cat.CAT;

    /**
     * The table <code>public.cat_cat</code>.
     */
    public static final CatCat CAT_CAT = CatCat.CAT_CAT;

    /**
     * The table <code>public.owner</code>.
     */
    public static final Owner OWNER = Owner.OWNER;
}
